#!/usr/bin/env python3
# This file is placed in the Public Domain
#
# pylint: disable=C,I,R


"build the package"


import os


NAME = "opr"


os.environ["PATH"] += ":cin"


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.strip())


print("\nCLEAN\n")
popen("clean")
print("\nTEST\n")
popen("pytest")
print("\n")
print("\nTAR\n")
popen("python3 setup.py sdist")
print("\nENV\n")
popen("mkenv")
print("\nWHEEL\n")
popen("python3 -m pip wheel -e .")
popen("mv *.whl dist")
print("\nTWINE\n")
popen("twine check dist/*")
